# Generated by Django 2.2.5 on 2020-05-20 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20200520_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_tpye',
            new_name='room_type',
        ),
    ]
